sudo: required

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker run -d -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=1 --name mysql mysql:8
  - sleep 10
  - docker exec -it  mysql mysql --database=mysql --execute "UPDATE user SET authentication_string='', plugin='mysql_native_password' WHERE user='root';"

language: node_js

node_js:
  - "6"
  - "8"
  - "10"
