sudo: required

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker run -d -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=1 --name mysql5 mysql:5
  - docker run -d -p 3307:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=1 --name mysql8-native-password mysql:8 --default-authentication-plugin=mysql_native_password
  - docker run -d -p 3308:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=1 --name mysql8 mysql:8
  - sleep 30

language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "12"
