name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql5:
        image: mysql:5
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      mysql8-native-password:
        image: mysql:8
        ports:
          - 3307:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        options: >-
          --default-authentication-plugin=mysql_native_password
      mysql8:
        image: mysql:8
        ports:
          - 3308:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: sleep 30
      - run: npm ci
      - run: npm run lint
      - run: npm test

  code-climate:
    needs: build
    runs-on: ubuntu-latest
    services:
      mysql5:
        image: mysql:5
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      mysql8-native-password:
        image: mysql:8
        ports:
          - 3307:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        options: >-
          --default-authentication-plugin=mysql_native_password
      mysql8:
        image: mysql:8
        ports:
          - 3308:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: sleep 30
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: npm run coverage
      - run: ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
      - run: ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
